server:
  port: 9002

#eureka配置
eureka:
  instance:
    hostname: eurekaServer9001
  client:
    register-with-eureka: false  #是否将自己注册给eureka server（默认为true）
    fetch-registry: false  #是否启用从注册中心拉取服务列表功能（默认为true）
    service-url:
      #将9000注册给9001，同时，也要将9001注册给9000
      defaultZone: http://eurekaServer9000:9000/eureka/
  server:
    enable-self-preservation: false  #关闭自我保护机制
