server:
  port: 10004
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rx2003414

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

#eureka配置
eureka:
  client:
    service-url:
      #将自己注册给defaultZone所指定的eureka server集群上
      defaultZone: http://eurekaServer9000:9000/eureka/,http://eurekaServer9001:9001/eureka/
  instance:
    prefer-ip-address: true  #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 10  #续约间隔时间
    lease-expiration-duration-in-seconds: 30  #续约到期时间

elm:
  jwt:
    location: classpath:elm.jks
    alias: elm
    password: hmall123
    tokenTTL: 30m
